### ISSUE TITLE
Oxidation

### ISSUE THREAD

**Issue by Taha-Firoz** [SaadBazaz/antiPixel#2]
After very briefly going through your code I think it's a prime candidate to be converted into rust. 

I don't want to do it just because we can, I really believe this particular code base can really benefit from rusts ergonomics. Also a few changes might be needed like changing the config file to be yaml or json but we can discuss that after it's been decided to proceed.

**Comment by SaadBazaz** [comment]
Hello Taha,
Glad to see your interest. Even though I'm a little rusty in Rust, I'm willing to learn more and make the switch.
Reflection is a good feature (if Rust supports it) which this program could greatly benefit from. 
How do we start?

**Comment by Taha-Firoz** [comment]
How will reflection benifit the program?
I think we should add a GitHub project that outlines what modules are to be implemented.

I really don't want to implement a `bmp` reader from scratch since theirs a great [bmp reader crate](https://crates.io/crates/bmp)

I need to know how you're encoding it rn, also maybe set up a Travis CI and write up some test cases to make sure the rust version is working correctly.

**Comment by SaadBazaz** [comment]
Reflection allows for easier and more dynamic configuration... For a photo/animation editor it's perfect. The fact that this could feature such easy configuration could make it a nice competitor to conventional Image Manipulation software written in C++. 

Of course, also why stop at BMP? Using third-party crates we can handle all sorts of file formats... I've also been bent on creating my own format so if you have any ideas we can throw it in the mix. 

There's not much to it right now... It just reads the Header of the file, then accordingly sets the Endian and loops over binary. Every three binaries are actually RGB values from 0 to 255. 

These values are then checked through hardcoded values (in Color.h).

**Comment by SaadBazaz** [comment]
Correction: I just read up a bit. Rust does not support reflection but may have something similar.
https://stackoverflow.com/questions/36416773/how-does-rust-implement-reflection

**Comment by Taha-Firoz** [comment]
I would really suggest we just focus on implementing the current c++ version in rust and the move on to a GUI and other file formats.

Can you make the GitHub project and outline what exactly needs to be implemented excluding the bmp file reading.

**Comment by SaadBazaz** [comment]
On it. 

Sharing for reference...
Basic outline:
- Setup BMP file-reading in Rust and extracting pixel information (RGB or CMYK colors). Since BMPs come in multiple forms (16 color BMP, 24-bit BMP, etc) the library must handle all of them and give correct info.
- Write the most optimized code as a boilerplate for displaying graphics in MASM
- Convert pixel information to array code according to a metric (in the current case, Color.h)

Further possible ideas:
- Automatic color detection, using Color Wheels or similar concepts and adjust them to VGA / MASM-supported colors.
- Support for TASM, NASM and other assemblers. Also support for high-level languages like C#, C++ and Rust.
- Basic animation-maker: Create keyframes right inside antiPixel and get optimized boilerplate code to run those keyframes as proper animations

**Comment by Taha-Firoz** [comment]
Okay so I've created a new branch I've setup the structure for the main anti pixel binary and the test cases. I've also added a travis file but github actions are looking promising too...

**Comment by SaadBazaz** [comment]
Closing, because the Oxidation process has begun
